- platform: unifi
  host: !secret unifi_host
  port: 443
  username: !secret unifi_username
  password: !secret unifi_password
  track_new_devices: false
  monitored_conditions:
    - _id
    - _is_guest_by_uap
    - _last_seen_by_uap
    - _uptime_by_uap
    - ap_mac
    - assoc_time
    - authorized
    - bssid
    - bytes-r
    - ccq
    - channel
    - essid
    - first_seen
    - hostname
    - idletime
    - ip
    - is_11r
    - is_guest
    - is_wired
    - last_seen
    - latest_assoc_time
    - mac
    - name
    - noise
    - noted
    - oui
    - powersave_enabled
    - qos_policy_applied
    - radio
    - radio_proto
    - rssi
    - rx_bytes
    - rx_bytes-r
    - rx_packets
    - rx_rate
    - signal
    - site_id
    - tx_bytes
    - tx_bytes-r
    - tx_packets
    - tx_power
    - tx_rate
    - uptime
    - user_id
    - usergroup_id
    - vlan
