- platform: mqtt
  name: "Robbie's Fan"
  state_topic: "robbies_room_fan/on/state"
  command_topic: "robbies_room_fan/on/set"
  oscillation_state_topic: "robbies_room_fan/oscillate/state"
  oscillation_command_topic: "robbies_room_fan/oscillate/set"
  speed_state_topic: "robbies_room_fan/speed/state"
  speed_command_topic: "robbies_room_fan/speed/set"
  qos: 0
  payload_on: "true"
  payload_off: "false"
  payload_oscillation_on: "true"
  payload_oscillation_off: "false"
  availability_topic: "robbies_room_fan/status"
  payload_available: "alive"
  payload_not_available: "dead"
  speeds:
    - 'off'
    - eco
    - low
    - medium
    - high
