- id: someone_arrived_home
  alias: Someone arrived home
  trigger:
  - entity_id: person.robbie_trencheny, person.eddie_sun
    from: not_home
    platform: state
    to: home
  action:
  - data:
      data:
        push:
          sound: US-EN-Morgan-Freeman-Roommate-Is-Arriving.wav
    data_template:
      message: '{{ trigger.to_state.attributes.friendly_name }} has arrived at home.

        {% for name, zone in states.person|groupby(''state'') %}{% if zone|length
        > 0 %}{% for device in zone %}{% if loop.last and loop|length > 1 %} and {%
        elif not loop.first and loop|length > 1 %}, {% endif %}{{ device.name }}{%
        endfor %}{% if zone|length == 1 %} is{% if name != "not_home" %} at{% endif
        %}{% else %} are{% endif %} {{ name|replace(''_'', '' '') }}.{% endif %} {%
        endfor %}

        '
      title: Roommate has arrived at home
    service: notify.humansanddisplays
- id: someone_left_home
  alias: Someone left home
  trigger:
  - entity_id: person.robbie_trencheny, person.eddie_sun
    from: home
    platform: state
    to: not_home
  action:
  - data_template:
      message: '{{ trigger.to_state.attributes.friendly_name }} has left home.

        {% for name, zone in states.person|groupby(''state'') %}{% if zone|length
        > 0 %}{% for device in zone %}{% if loop.last and loop|length > 1 %} and {%
        elif not loop.first and loop|length > 1 %}, {% endif %}{{ device.name }}{%
        endfor %}{% if zone|length == 1 %} is{% if name != "not_home" %} at{% endif
        %}{% else %} are{% endif %} {{ name|replace(''_'', '' '') }}.{% endif %} {%
        endfor %}

        '
      title: Roommate has left home
    service: notify.humansanddisplays
- alias: Set dishwasher active when power detected
  id: set_dishwasher_active
  trigger:
  - platform: numeric_state
    entity_id: sensor.dishwasher_power
    above: 10
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: input_select.dishwasher_status
      state: Dirty
    - condition: state
      entity_id: input_select.dishwasher_status
      state: Clean
    - condition: state
      entity_id: input_select.dishwasher_status
      state: Drying
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.dishwasher_status
      option: Running
- alias: Set dishwasher drying when power drops
  id: set_dishwasher_drying
  trigger:
  - platform: numeric_state
    entity_id: sensor.dishwasher_power
    below: 10
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_select.dishwasher_status
      state: Running
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.dishwasher_status
      option: Drying
- alias: Set dishwasher clean
  id: set_dishwasher_clean
  trigger:
  - platform: state
    entity_id: input_select.dishwasher_status
    to: Drying
    for:
      minutes: 15
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_select.dishwasher_status
      state: Drying
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.dishwasher_status
      option: Clean
- alias: Set Dishwasher dirty when power off
  id: set_dishwasher_dirty
  trigger:
  - platform: numeric_state
    entity_id: sensor.dishwasher_power
    below: 1
  condition:
    condition: and
    conditions:
    - condition: numeric_state
      entity_id: sensor.dishwasher_power
      below: 1
    - condition: or
      conditions:
      - condition: state
        entity_id: input_select.dishwasher_status
        state: Clean
      - condition: state
        entity_id: input_select.dishwasher_status
        state: Drying
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.dishwasher_status
      option: Dirty
- alias: Send alert when dishwasher is clean
  id: send_dishwasher_alert
  trigger:
  - platform: state
    entity_id: input_select.dishwasher_status
    to: Clean
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_select.dishwasher_status
      state: Clean
  action:
  - service: notify.humansanddisplays
    data:
      message: The Dishwasher has finished and is ready to be emptied!
      title: Dishwasher Update
- alias: Turn off all devices when everyone leaves home
  id: turn_off_when_people_leave
  trigger:
    platform: state
    entity_id: group.all_devices
    from: home
    to: not_home
  action:
    service: homeassistant.turn_off
- alias: Send notifications for package delivery
  id: package_notifications
  trigger:
    platform: event
    event_type: security.package_ready
  action:
    service_template: 'notify.{{ trigger.event.data.human }}iOSApp

      '
    data_template:
      message: 'You have {{ trigger.event.data.number_of_ready_packages }} package(s)
        ready to be picked up.

        '
    data:
      title: Packages available
      data:
        push:
          sound: US-EN-Alexa-Mail-Has-Arrived.wav
- alias: Send notifications for guests/misc calls from front desk
  id: guest_notification
  trigger:
    platform: event
    event_type: security.delivery_access_request
  action:
    service_template: 'notify.{{ trigger.event.data.human }}iOSApp

      '
    data:
      title: Guest/delivery inbound
      message: You have a guest or delivery.
      data:
        push:
          sound: US-EN-Alexa-Mail-Has-Arrived.wav
- alias: Front door is open
  id: front_door_open
  trigger:
    platform: state
    entity_id: binary_sensor.front_door_sensor
    from: 'off'
    to: 'on'
  action:
    service: notify.humansanddisplays
    data:
      title: Front door
      message: The front door is open
      data:
        push:
          sound: US-EN-Daisy-Front-Door-Open.wav
- alias: Turn on entrance hallway overhead when the door opens
  id: turn_on_entrance_hallway
  trigger:
    platform: state
    entity_id: binary_sensor.front_door_sensor
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
    service: script.turn_on
    entity_id: script.1532904736916
- alias: Turn on living room lights when Apple TV is paused
  id: turn_on_living_room_when_atv_pauses
  trigger:
    platform: state
    entity_id: media_player.living_room_apple_tv
    from: playing
    to: paused
  condition:
    condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
    service: light.turn_on
    entity_id: group.living_room
    data:
      transition: 60
- alias: Turn off living room lights when Apple TV is playing
  id: turn_off_living_room_when_atv_plays
  trigger:
    platform: state
    entity_id: media_player.living_room_apple_tv
    from: paused
    to: playing
  condition:
    condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
    service: light.turn_off
    entity_id: group.living_room
- alias: Turn on Robbie's Room lights when Apple TV is paused
  id: turn_on_robbies_room_when_media_pauses
  trigger:
  - platform: state
    entity_id: media_player.robbies_room_apple_tv
    from: playing
    to: paused
  condition:
    condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
    service: light.turn_on
    entity_id: group.robbiesroom
    data:
      transition: 60
- alias: Turn off Robbie's Room lights when Apple TV is playing
  id: turn_off_robbies_room_when_media_plays
  trigger:
  - platform: state
    entity_id: media_player.robbies_room_apple_tv
    from: paused
    to: playing
  condition:
    condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
    service: light.turn_off
    entity_id: group.robbiesroom
- id: notify_motion_detected
  alias: Notify if motion detected in living room or hallway when no one is home
  trigger:
  - entity_id: binary_sensor.interior_hallway_motion_sensor, binary_sensor.living_room_multisensor_sensor
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: person.robbie_trencheny
    state: not_home
  - condition: state
    entity_id: person.eddie_sun
    state: not_home
  action:
  - data:
      data:
        push:
          sound: US-EN-Alexa-Motion-Detected-Generic.wav
    data_template:
      message: 'Motion detected on {{ trigger.to_state.attributes.friendly_name }}
        but no one is home!

        '
      title: Motion detected
    service: notify.allresidents
- id: robbie_arrived_home
  alias: Robbie arrived home
  trigger:
  - entity_id: person.robbie_trencheny
    from: not_home
    platform: state
    to: home
  action:
  - data:
      brightness: 255
      rgb_color:
      - 255
      - 255
      - 255
    entity_id: group.robbies_room
    service: light.turn_on
- id: robbie_left_home
  alias: Robbie left home
  trigger:
  - entity_id: person.robbie_trencheny
    from: home
    platform: state
    to: not_home
  action:
  - entity_id: group.robbiesroom
    service: script.turn_off
- id: robbies_door_open
  alias: Notify if Robbie's door is opened when he isn't home
  trigger:
  - entity_id: binary_sensor.robbies_bedroom_door_sensor
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: person.robbie_trencheny
    state: not_home
  action:
  - data_template:
      message: 'Bedroom door is {% if trigger.to_state.state == "on" %}open{% else
        %}closed{% endif %} (you aren''t at home!)

        '
    service: notify.robbiesdevices
- id: robbies_room_motion
  alias: Notify if there is motion in Robbie's Room when he isn't home
  trigger:
  - entity_id: binary_sensor.robbies_bedroom_multisensor_sensor
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: person.robbie_trencheny
    state: not_home
  action:
  - data:
      data:
        push:
          sound: US-EN-Morgan-Freeman-Motion-In-Bedroom.wav
      message: Motion in your bedroom (you aren't at home!)
    service: notify.robbiesdevices
- alias: Send a notification 1 hour before sunset
  id: before_sunset_notification
  trigger:
    platform: sun
    event: sunset
    offset: -01:00:00
  action:
    service: notify.robbiesdevices
    data:
      message: There is one hour remaining until sunset.
- id: sunset_notification
  alias: End of day sunset notification
  trigger:
  - event: sunset
    platform: sun
  action:
  - data:
      data:
        push:
          sound: US-EN-Alexa-Good-Night.wav
    data_template:
      message: 'Sunset for {{ now().strftime(''%A %B %-d, %Y at %-I:%M %p'') }}! The
        day''s high temperature in Oakland was {{ states.sensor.dark_sky_daytime_high_temperature_0d.state
        }}{{ states.sensor.dark_sky_daytime_high_temperature_0d.unit_of_measurement
        }}. The low temperature today was {{ states.sensor.dark_sky_daytime_low_temperature_0d.state
        }}{{ states.sensor.dark_sky_daytime_low_temperature_0d.unit_of_measurement
        }}. The current conditions are {{ states.sensor.dark_sky_minutely_summary.state|lower
        }}. {% for name, zone in states.person|groupby(''state'') %}{% if zone|length
        > 0 %}{% for device in zone %}{% if loop.last and loop|length > 1 %} and {%
        elif not loop.first and loop|length > 1 %}, {% endif %}{{ device.name }}{%
        endfor %}{% if zone|length == 1 %} is{% if name != "not_home" %} at{% endif
        %}{% else %} are{% endif %} {{ name|replace(''_'', '' '') }}.{% endif %} {%
        endfor %}

        '
    service: notify.robbiesdevices
- action:
  - alias: Turn on living room lights
    data:
      entity_id:
      - light.front_lamp
      - light.living_room_overhead_lights_level
      - light.living_room_window_led_strip
      - light.rear_lamp
    service: light.turn_on
  alias: Turn living room lights on when holding dimmer switch
  id: '1510187667467'
  trigger:
  - event_data:
      scene_id: 1
      scene_data: 3
    event_type: zwave.scene_activated
    platform: event
- action:
  - alias: Turn off living room lights
    data:
      entity_id:
      - light.front_lamp
      - light.living_room_overhead_lights_level
      - light.living_room_window_led_strip
      - light.rear_lamp
    service: light.turn_off
  alias: Turn living room lights off when holding dimmer switch
  id: '1510187667468'
  trigger:
  - event_data:
      scene_id: 2
      scene_data: 3
    event_type: zwave.scene_activated
    platform: event
- alias: Start HomeKit
  trigger:
  - platform: event
    event_type: zwave.network_ready
  - platform: event
    event_type: zwave.network_complete
  action:
  - service: homekit.start
  id: 510ba2270acd448ea87db01c598d19f4
- id: '1552385078690'
  alias: Set theme for night
  trigger:
  - event: sunset
    offset: 00:45:00
    platform: sun
  condition: []
  action:
  - data:
      name: midnight
    service: frontend.set_theme
- id: '1552385107202'
  alias: Set theme for day
  trigger:
  - event: sunrise
    offset: -00:30:00
    platform: sun
  condition: []
  action:
  - data:
      name: default
    service: frontend.set_theme
- id: '1552820217163'
  alias: Set Robbie's Fan Timer
  trigger:
  - entity_id: input_select.robbies_fan_timer
    platform: state
  condition: []
  action:
  - data:
      payload_template: '{{ states.input_select.robbies_fan_timer.state }}'
      topic: robbies_room_fan/wind/set
    service: mqtt.publish
- id: '1552820252245'
  alias: Set Robbie's Fan Wind Mode
  trigger:
  - entity_id: input_select.robbies_fan_wind
    platform: state
  condition: []
  action:
  - data:
      payload_template: '{{ states.input_select.robbies_fan_wind.state }}'
      topic: robbies_room_fan/wind/set
    service: mqtt.publish
