homeassistant:
  name: TwelveTwelve
  unit_system: imperial
  time_zone: America/Los_Angeles
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 8
  customize: !include_dir_merge_named customize
  customize_glob:
    "media_player.plex_*":
      alexa_hidden: true

auth:

http:
  base_url: !secret http_base_url
  use_x_forwarded_for: yes
  trusted_proxies:
    - 127.0.0.1
    - ::1

config:

mqtt:
  broker: 192.168.1.3
  port: 1883
  client_id: home-assistant
  username: !secret mqtt_username
  password: !secret mqtt_password

system_health:

zwave:
  usb_path: /dev/zwave
  config_path: /home/robbiet480/home-assistant/venv/lib/python3.5/site-packages/python_openzwave/ozw_config
  network_key: !secret zwave_network_key
  device_config: !include zwave_device_config.yaml

discovery:

logger:
  default: info
  logs:
    pyhap: warning
frontend:
  themes: !include themes.yaml
map:
history:
sun:
logbook:
updater:
recorder:
  db_url: !secret recorder_db_url
  purge_interval: 2
  purge_keep_days: 14

ios:

mobile_app:

tradfri:
  host: !secret tradfri_ip
  allow_tradfri_groups: false

alexa:
  flash_briefings: !include_dir_named alexa/flash_briefings/
automation: !include automations.yaml
binary_sensor: !include_dir_merge_list devices/binary_sensors/
camera: !include_dir_merge_list devices/cameras/
device_tracker: !include_dir_merge_list devices/device_trackers/
fan: !include_dir_merge_list devices/fans/
group: !include_dir_named groups/
intent_script: !include_dir_named alexa/intents/
light: !include_dir_merge_list devices/lights/
media_player: !include_dir_merge_list devices/media_players/
notify: !include_dir_merge_list notifies/
script: !include scripts.yaml
sensor: !include_dir_merge_list devices/sensors/
switch: !include_dir_merge_list devices/switches/
zone: !include_dir_merge_list zones/

apple_tv:

cloud:
  alexa:
    filter:
      include_domains:
        - fan
        - light
        - media_player
        - switch

homekit:
  auto_start: False

speedtestdotnet:
  scan_interval:
    minutes: 30

lametric:
  client_id: !secret lametric_client_id
  client_secret: !secret lametric_client_secret
