homeassistant:
  name: TwelveTwelve
  unit_system: imperial
  time_zone: America/Los_Angeles
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 8
  customize: !include_dir_merge_named customize
  customize_glob:
    "media_player.plex_*":
      alexa_hidden: true

http:
  use_x_forwarded_for: yes
  trusted_proxies:
    - 127.0.0.1
    - ::1

config:

system_health:

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_network_key
  device_config: !include zwave_device_config.yaml

discovery:

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state

logger:
  default: info
  logs:
    pyhap: warning
    homeassistant.components.onkyo.media_player: warning
    homeassistant.components.mobile_app: debug
frontend:
  themes: !include themes.yaml
lovelace:
  mode: yaml
map:
history:
sun:
logbook:
updater:
recorder:
  db_url: !secret recorder_db_url
  purge_keep_days: 14

mobile_app:

alexa:
automation: !include automations.yaml
binary_sensor: !include_dir_merge_list devices/binary_sensors/
camera: !include_dir_merge_list devices/cameras/
group: !include_dir_named groups/
intent_script: !include_dir_named alexa/intents/
input_select: !include_dir_named input_selects/
light: !include_dir_merge_list devices/lights/
media_player: !include_dir_merge_list devices/media_players/
notify: !include_dir_merge_list notifies/
script: !include scripts.yaml
sensor: !include_dir_merge_list devices/sensors/
switch: !include_dir_merge_list devices/switches/

apple_tv:

cloud:
  alexa:
    filter:
      include_entities:
        - media_player.living_room_apple_tv_4k
        - media_player.robbies_room_apple_tv
      include_domains:
        - fan
        - light
        - switch

homekit:
  auto_start: False
  filter:
    include_domains:
      - fan
      - light
      - switch
      - camera
      - binary_sensor
      - device_tracker
      - person
      - media_player
      - sensor

speedtestdotnet:
  scan_interval:
    minutes: 30

lametric:
  client_id: !secret lametric_client_id
  client_secret: !secret lametric_client_secret

amcrest:
  - host: 192.168.1.46
    username: !secret amcrest_username
    password: !secret amcrest_password
    resolution: high

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret
