- platform: darksky
  api_key: !secret forecast_io_key
  forecast:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
  monitored_conditions:
    - apparent_temperature
    - apparent_temperature_high
    - apparent_temperature_low
    - cloud_cover
    - daily_summary
    - dew_point
    - hourly_summary
    - humidity
    - icon
    - minutely_summary
    - nearest_storm_bearing
    - nearest_storm_distance
    - ozone
    - precip_accumulation
    - precip_intensity
    - precip_intensity_max
    - precip_probability
    - precip_type
    - pressure
    - summary
    - temperature
    - temperature_high
    - temperature_low
    - uv_index
    - visibility
    - wind_bearing
    - wind_speed
